title: Software Testing With Fun!
author:
  name: Satheesh Rajendran
  email: sathnaga86@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog that would concentrate on software testing
  techniques and tools for linux, KVM areas and DevOps.

show_excerpts: false

minima:
  social_links:
    twitter: sathnaga86
    github: sathnaga
    linkedin: sathnaga86

google_analytics: UA-131048348-1

header_pages:
 - about.md
 - bio.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
